"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from pumble_keys.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .addreaction import (
        AddReactionRequest,
        AddReactionRequestTypedDict,
        AddReactionResponse,
        AddReactionResponseTypedDict,
    )
    from .adduserstochannel import (
        AddUsersToChannelRequest,
        AddUsersToChannelRequestTypedDict,
    )
    from .createchannel import CreateChannelRequest, CreateChannelRequestTypedDict
    from .createscheduledmessage import (
        CreateScheduledMessageRequest,
        CreateScheduledMessageRequestTypedDict,
    )
    from .customstatus import CustomStatusRequest, CustomStatusRequestTypedDict
    from .deletemessage import DeleteMessageRequest, DeleteMessageRequestTypedDict
    from .deletescheduledmessage import (
        DeleteScheduledMessageRequest,
        DeleteScheduledMessageRequestTypedDict,
    )
    from .dmgroup import DmGroupRequest, DmGroupRequestTypedDict
    from .dmuser import DmUserRequest, DmUserRequestTypedDict
    from .editmessage import EditMessageRequest, EditMessageRequestTypedDict
    from .editscheduledmessage import (
        EditScheduledMessageRequest,
        EditScheduledMessageRequestTypedDict,
    )
    from .fetchmessage import FetchMessageRequest, FetchMessageRequestTypedDict
    from .fetchscheduledmessage import (
        FetchScheduledMessageRequest,
        FetchScheduledMessageRequestTypedDict,
    )
    from .fetchscheduledmessages import (
        FetchScheduledMessagesRequest,
        FetchScheduledMessagesRequestTypedDict,
        FetchScheduledMessagesResponse,
        FetchScheduledMessagesResponseTypedDict,
    )
    from .fetchthreadreplies import (
        FetchThreadRepliesRequest,
        FetchThreadRepliesRequestTypedDict,
        FetchThreadRepliesResponse,
        FetchThreadRepliesResponseTypedDict,
    )
    from .getchannel import (
        GetChannelRequest,
        GetChannelRequestTypedDict,
        GetChannelResponse,
        GetChannelResponseTypedDict,
    )
    from .listmessages import (
        ListMessagesRequest,
        ListMessagesRequestTypedDict,
        ListMessagesResponse,
        ListMessagesResponseTypedDict,
    )
    from .removereaction import (
        RemoveReactionRequest,
        RemoveReactionRequestTypedDict,
        RemoveReactionResponse,
        RemoveReactionResponseTypedDict,
    )
    from .removeuserfromchannel import (
        RemoveUserFromChannelRequest,
        RemoveUserFromChannelRequestTypedDict,
    )
    from .searchmessages import (
        SearchMessagesRequest,
        SearchMessagesRequestTypedDict,
        SearchMessagesResponse,
        SearchMessagesResponseTypedDict,
    )
    from .sendmessage import (
        SendMessageRequest,
        SendMessageRequestBody1,
        SendMessageRequestBody1TypedDict,
        SendMessageRequestBody2,
        SendMessageRequestBody2TypedDict,
        SendMessageRequestTypedDict,
    )
    from .sendreply import (
        SendReplyRequest,
        SendReplyRequestBody1,
        SendReplyRequestBody1TypedDict,
        SendReplyRequestBody2,
        SendReplyRequestBody2TypedDict,
        SendReplyRequestTypedDict,
    )

__all__ = [
    "AddReactionRequest",
    "AddReactionRequestTypedDict",
    "AddReactionResponse",
    "AddReactionResponseTypedDict",
    "AddUsersToChannelRequest",
    "AddUsersToChannelRequestTypedDict",
    "CreateChannelRequest",
    "CreateChannelRequestTypedDict",
    "CreateScheduledMessageRequest",
    "CreateScheduledMessageRequestTypedDict",
    "CustomStatusRequest",
    "CustomStatusRequestTypedDict",
    "DeleteMessageRequest",
    "DeleteMessageRequestTypedDict",
    "DeleteScheduledMessageRequest",
    "DeleteScheduledMessageRequestTypedDict",
    "DmGroupRequest",
    "DmGroupRequestTypedDict",
    "DmUserRequest",
    "DmUserRequestTypedDict",
    "EditMessageRequest",
    "EditMessageRequestTypedDict",
    "EditScheduledMessageRequest",
    "EditScheduledMessageRequestTypedDict",
    "FetchMessageRequest",
    "FetchMessageRequestTypedDict",
    "FetchScheduledMessageRequest",
    "FetchScheduledMessageRequestTypedDict",
    "FetchScheduledMessagesRequest",
    "FetchScheduledMessagesRequestTypedDict",
    "FetchScheduledMessagesResponse",
    "FetchScheduledMessagesResponseTypedDict",
    "FetchThreadRepliesRequest",
    "FetchThreadRepliesRequestTypedDict",
    "FetchThreadRepliesResponse",
    "FetchThreadRepliesResponseTypedDict",
    "GetChannelRequest",
    "GetChannelRequestTypedDict",
    "GetChannelResponse",
    "GetChannelResponseTypedDict",
    "ListMessagesRequest",
    "ListMessagesRequestTypedDict",
    "ListMessagesResponse",
    "ListMessagesResponseTypedDict",
    "RemoveReactionRequest",
    "RemoveReactionRequestTypedDict",
    "RemoveReactionResponse",
    "RemoveReactionResponseTypedDict",
    "RemoveUserFromChannelRequest",
    "RemoveUserFromChannelRequestTypedDict",
    "SearchMessagesRequest",
    "SearchMessagesRequestTypedDict",
    "SearchMessagesResponse",
    "SearchMessagesResponseTypedDict",
    "SendMessageRequest",
    "SendMessageRequestBody1",
    "SendMessageRequestBody1TypedDict",
    "SendMessageRequestBody2",
    "SendMessageRequestBody2TypedDict",
    "SendMessageRequestTypedDict",
    "SendReplyRequest",
    "SendReplyRequestBody1",
    "SendReplyRequestBody1TypedDict",
    "SendReplyRequestBody2",
    "SendReplyRequestBody2TypedDict",
    "SendReplyRequestTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AddReactionRequest": ".addreaction",
    "AddReactionRequestTypedDict": ".addreaction",
    "AddReactionResponse": ".addreaction",
    "AddReactionResponseTypedDict": ".addreaction",
    "AddUsersToChannelRequest": ".adduserstochannel",
    "AddUsersToChannelRequestTypedDict": ".adduserstochannel",
    "CreateChannelRequest": ".createchannel",
    "CreateChannelRequestTypedDict": ".createchannel",
    "CreateScheduledMessageRequest": ".createscheduledmessage",
    "CreateScheduledMessageRequestTypedDict": ".createscheduledmessage",
    "CustomStatusRequest": ".customstatus",
    "CustomStatusRequestTypedDict": ".customstatus",
    "DeleteMessageRequest": ".deletemessage",
    "DeleteMessageRequestTypedDict": ".deletemessage",
    "DeleteScheduledMessageRequest": ".deletescheduledmessage",
    "DeleteScheduledMessageRequestTypedDict": ".deletescheduledmessage",
    "DmGroupRequest": ".dmgroup",
    "DmGroupRequestTypedDict": ".dmgroup",
    "DmUserRequest": ".dmuser",
    "DmUserRequestTypedDict": ".dmuser",
    "EditMessageRequest": ".editmessage",
    "EditMessageRequestTypedDict": ".editmessage",
    "EditScheduledMessageRequest": ".editscheduledmessage",
    "EditScheduledMessageRequestTypedDict": ".editscheduledmessage",
    "FetchMessageRequest": ".fetchmessage",
    "FetchMessageRequestTypedDict": ".fetchmessage",
    "FetchScheduledMessageRequest": ".fetchscheduledmessage",
    "FetchScheduledMessageRequestTypedDict": ".fetchscheduledmessage",
    "FetchScheduledMessagesRequest": ".fetchscheduledmessages",
    "FetchScheduledMessagesRequestTypedDict": ".fetchscheduledmessages",
    "FetchScheduledMessagesResponse": ".fetchscheduledmessages",
    "FetchScheduledMessagesResponseTypedDict": ".fetchscheduledmessages",
    "FetchThreadRepliesRequest": ".fetchthreadreplies",
    "FetchThreadRepliesRequestTypedDict": ".fetchthreadreplies",
    "FetchThreadRepliesResponse": ".fetchthreadreplies",
    "FetchThreadRepliesResponseTypedDict": ".fetchthreadreplies",
    "GetChannelRequest": ".getchannel",
    "GetChannelRequestTypedDict": ".getchannel",
    "GetChannelResponse": ".getchannel",
    "GetChannelResponseTypedDict": ".getchannel",
    "ListMessagesRequest": ".listmessages",
    "ListMessagesRequestTypedDict": ".listmessages",
    "ListMessagesResponse": ".listmessages",
    "ListMessagesResponseTypedDict": ".listmessages",
    "RemoveReactionRequest": ".removereaction",
    "RemoveReactionRequestTypedDict": ".removereaction",
    "RemoveReactionResponse": ".removereaction",
    "RemoveReactionResponseTypedDict": ".removereaction",
    "RemoveUserFromChannelRequest": ".removeuserfromchannel",
    "RemoveUserFromChannelRequestTypedDict": ".removeuserfromchannel",
    "SearchMessagesRequest": ".searchmessages",
    "SearchMessagesRequestTypedDict": ".searchmessages",
    "SearchMessagesResponse": ".searchmessages",
    "SearchMessagesResponseTypedDict": ".searchmessages",
    "SendMessageRequest": ".sendmessage",
    "SendMessageRequestBody1": ".sendmessage",
    "SendMessageRequestBody1TypedDict": ".sendmessage",
    "SendMessageRequestBody2": ".sendmessage",
    "SendMessageRequestBody2TypedDict": ".sendmessage",
    "SendMessageRequestTypedDict": ".sendmessage",
    "SendReplyRequest": ".sendreply",
    "SendReplyRequestBody1": ".sendreply",
    "SendReplyRequestBody1TypedDict": ".sendreply",
    "SendReplyRequestBody2": ".sendreply",
    "SendReplyRequestBody2TypedDict": ".sendreply",
    "SendReplyRequestTypedDict": ".sendreply",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
