"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AddReactionRequestTypedDict(TypedDict):
    message_id: str
    reaction: str
    r"""Emoji code in `:emoji_name:` form (e.g. `:+1:`)."""
    channel_id: NotRequired[str]
    skin_tone: NotRequired[int]


class AddReactionRequest(BaseModel):
    message_id: Annotated[str, pydantic.Field(alias="messageId")]

    reaction: str
    r"""Emoji code in `:emoji_name:` form (e.g. `:+1:`)."""

    channel_id: Annotated[Optional[str], pydantic.Field(alias="channelId")] = None

    skin_tone: Annotated[Optional[int], pydantic.Field(alias="skinTone")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channelId", "skinTone"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class AddReactionResponseTypedDict(TypedDict):
    r"""Reaction added."""

    status: NotRequired[str]


class AddReactionResponse(BaseModel):
    r"""Reaction added."""

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AddReactionRequest.model_rebuild()
except NameError:
    pass
