"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class AddUsersToChannelRequestTypedDict(TypedDict):
    channel_id: str
    user_ids: List[str]


class AddUsersToChannelRequest(BaseModel):
    channel_id: Annotated[str, pydantic.Field(alias="channelId")]

    user_ids: Annotated[List[str], pydantic.Field(alias="userIds")]


try:
    AddUsersToChannelRequest.model_rebuild()
except NameError:
    pass
