"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys import models
from pumble_keys.models import channeltype as models_channeltype
from pumble_keys.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateChannelRequestTypedDict(TypedDict):
    name: str
    r"""Channel name. Pumble normalizes this server-side
    (lower-cases, replaces spaces with `-`).

    """
    type: models_channeltype.ChannelType
    r"""Visibility of a channel."""
    description: NotRequired[str]
    r"""Optional channel description."""


class CreateChannelRequest(BaseModel):
    name: str
    r"""Channel name. Pumble normalizes this server-side
    (lower-cases, replaces spaces with `-`).

    """

    type: models_channeltype.ChannelType
    r"""Visibility of a channel."""

    description: Optional[str] = None
    r"""Optional channel description."""

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return models.ChannelType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
