"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.models import (
    messageblock as models_messageblock,
    recurrence as models_recurrence,
)
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateScheduledMessageRequestTypedDict(TypedDict):
    channel_id: str
    text: str
    send_at: int
    r"""Delivery moment (epoch ms). Must be in the future."""
    blocks: NotRequired[List[models_messageblock.MessageBlockTypedDict]]
    thread_root_id: NotRequired[str]
    r"""If set, the scheduled message will be sent as a thread reply."""
    also_send_to_channel: NotRequired[bool]
    recurrence: NotRequired[models_recurrence.RecurrenceTypedDict]


class CreateScheduledMessageRequest(BaseModel):
    channel_id: Annotated[str, pydantic.Field(alias="channelId")]

    text: str

    send_at: Annotated[int, pydantic.Field(alias="sendAt")]
    r"""Delivery moment (epoch ms). Must be in the future."""

    blocks: Optional[List[models_messageblock.MessageBlock]] = None

    thread_root_id: Annotated[Optional[str], pydantic.Field(alias="threadRootId")] = (
        None
    )
    r"""If set, the scheduled message will be sent as a thread reply."""

    also_send_to_channel: Annotated[
        Optional[bool], pydantic.Field(alias="alsoSendToChannel")
    ] = None

    recurrence: Optional[models_recurrence.Recurrence] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["blocks", "threadRootId", "alsoSendToChannel", "recurrence"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateScheduledMessageRequest.model_rebuild()
except NameError:
    pass
