"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CustomStatusRequestTypedDict(TypedDict):
    code: str
    r"""Emoji code in `:emoji_name:` form."""
    expires_at: int
    r"""Epoch-ms moment to clear the status (0 = never)."""
    status: NotRequired[str]
    r"""Free-form status text."""


class CustomStatusRequest(BaseModel):
    code: str
    r"""Emoji code in `:emoji_name:` form."""

    expires_at: Annotated[int, pydantic.Field(alias="expiresAt")]
    r"""Epoch-ms moment to clear the status (0 = never)."""

    status: Optional[str] = None
    r"""Free-form status text."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CustomStatusRequest.model_rebuild()
except NameError:
    pass
