"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel
from pumble_keys.utils import FieldMetadata, QueryParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class DeleteScheduledMessageRequestTypedDict(TypedDict):
    scheduled_message_id: str


class DeleteScheduledMessageRequest(BaseModel):
    scheduled_message_id: Annotated[
        str,
        pydantic.Field(alias="scheduledMessageId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]
