"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DmGroupRequestTypedDict(TypedDict):
    user_ids: List[str]
    text: str
    as_bot: NotRequired[bool]


class DmGroupRequest(BaseModel):
    user_ids: Annotated[List[str], pydantic.Field(alias="userIds")]

    text: str

    as_bot: Annotated[Optional[bool], pydantic.Field(alias="asBot")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["asBot"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    DmGroupRequest.model_rebuild()
except NameError:
    pass
