"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.models import (
    messageblock as models_messageblock,
    recurrence as models_recurrence,
)
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class EditScheduledMessageRequestTypedDict(TypedDict):
    scheduled_message_id: str
    channel_id: str
    text: str
    send_at: int
    r"""Delivery moment (epoch ms). Required even if unchanged."""
    blocks: NotRequired[List[models_messageblock.MessageBlockTypedDict]]
    recurrence: NotRequired[models_recurrence.RecurrenceTypedDict]


class EditScheduledMessageRequest(BaseModel):
    scheduled_message_id: Annotated[str, pydantic.Field(alias="scheduledMessageId")]

    channel_id: Annotated[str, pydantic.Field(alias="channelId")]

    text: str

    send_at: Annotated[int, pydantic.Field(alias="sendAt")]
    r"""Delivery moment (epoch ms). Required even if unchanged."""

    blocks: Optional[List[models_messageblock.MessageBlock]] = None

    recurrence: Optional[models_recurrence.Recurrence] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["blocks", "recurrence"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    EditScheduledMessageRequest.model_rebuild()
except NameError:
    pass
