"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.models import messageblock as models_messageblock
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class EditMessageRequestTypedDict(TypedDict):
    message_id: str
    channel_id: str
    text: str
    blocks: NotRequired[List[models_messageblock.MessageBlockTypedDict]]


class EditMessageRequest(BaseModel):
    message_id: Annotated[str, pydantic.Field(alias="messageId")]

    channel_id: Annotated[str, pydantic.Field(alias="channelId")]

    text: str

    blocks: Optional[List[models_messageblock.MessageBlock]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["blocks"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    EditMessageRequest.model_rebuild()
except NameError:
    pass
