"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.models import message as models_message
from pumble_keys.types import BaseModel, UNSET_SENTINEL
from pumble_keys.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Awaitable, Callable, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class FetchThreadRepliesRequestTypedDict(TypedDict):
    root_message_id: str
    channel_id: NotRequired[str]
    channel: NotRequired[str]
    cursor: NotRequired[str]
    r"""ID of the last reply on the previous page."""
    limit: NotRequired[int]


class FetchThreadRepliesRequest(BaseModel):
    root_message_id: Annotated[
        str,
        pydantic.Field(alias="rootMessageId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]

    channel_id: Annotated[
        Optional[str],
        pydantic.Field(alias="channelId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    channel: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""ID of the last reply on the previous page."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channelId", "channel", "cursor", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class FetchThreadRepliesResponseTypedDict(TypedDict):
    result: List[models_message.MessageTypedDict]


class FetchThreadRepliesResponse(BaseModel):
    next: Union[
        Callable[[], Optional[FetchThreadRepliesResponse]],
        Callable[[], Awaitable[Optional[FetchThreadRepliesResponse]]],
    ]

    result: List[models_message.Message]
