"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.models import scheduledmessagelist as models_scheduledmessagelist
from pumble_keys.types import BaseModel, UNSET_SENTINEL
from pumble_keys.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Awaitable, Callable, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class FetchScheduledMessagesRequestTypedDict(TypedDict):
    channel_id: NotRequired[str]
    cursor: NotRequired[str]
    limit: NotRequired[int]


class FetchScheduledMessagesRequest(BaseModel):
    channel_id: Annotated[
        Optional[str],
        pydantic.Field(alias="channelId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channelId", "cursor", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class FetchScheduledMessagesResponseTypedDict(TypedDict):
    result: models_scheduledmessagelist.ScheduledMessageListTypedDict


class FetchScheduledMessagesResponse(BaseModel):
    next: Union[
        Callable[[], Optional[FetchScheduledMessagesResponse]],
        Callable[[], Awaitable[Optional[FetchScheduledMessagesResponse]]],
    ]

    result: models_scheduledmessagelist.ScheduledMessageList
