"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.models import channel as models_channel
from pumble_keys.types import BaseModel, UNSET_SENTINEL
from pumble_keys.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetChannelRequestTypedDict(TypedDict):
    channel_id: NotRequired[str]
    channel: NotRequired[str]


class GetChannelRequest(BaseModel):
    channel_id: Annotated[
        Optional[str],
        pydantic.Field(alias="channelId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    channel: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channelId", "channel"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetChannelResponseTypedDict(TypedDict):
    r"""Channel details."""

    channel: models_channel.ChannelTypedDict


class GetChannelResponse(BaseModel):
    r"""Channel details."""

    channel: models_channel.Channel
