"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.models import (
    listmessagesstrategy as models_listmessagesstrategy,
    messagelist as models_messagelist,
)
from pumble_keys.types import BaseModel, UNSET_SENTINEL
from pumble_keys.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Awaitable, Callable, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class ListMessagesRequestTypedDict(TypedDict):
    channel_id: NotRequired[str]
    channel: NotRequired[str]
    cursor: NotRequired[str]
    r"""ID of the last message on the previous page."""
    limit: NotRequired[int]
    strategy: NotRequired[models_listmessagesstrategy.ListMessagesStrategy]
    r"""Pagination direction relative to `cursor`. When `cursor` is omitted the
    server returns the most-recent page regardless of `strategy`.

    """


class ListMessagesRequest(BaseModel):
    channel_id: Annotated[
        Optional[str],
        pydantic.Field(alias="channelId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    channel: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""ID of the last message on the previous page."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 100

    strategy: Annotated[
        Optional[models_listmessagesstrategy.ListMessagesStrategy],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Pagination direction relative to `cursor`. When `cursor` is omitted the
    server returns the most-recent page regardless of `strategy`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channelId", "channel", "cursor", "limit", "strategy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListMessagesResponseTypedDict(TypedDict):
    result: models_messagelist.MessageListTypedDict


class ListMessagesResponse(BaseModel):
    next: Union[
        Callable[[], Optional[ListMessagesResponse]],
        Callable[[], Awaitable[Optional[ListMessagesResponse]]],
    ]

    result: models_messagelist.MessageList
