"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class RemoveUserFromChannelRequestTypedDict(TypedDict):
    channel_id: str
    user_id: str


class RemoveUserFromChannelRequest(BaseModel):
    channel_id: Annotated[str, pydantic.Field(alias="channelId")]

    user_id: Annotated[str, pydantic.Field(alias="userId")]


try:
    RemoveUserFromChannelRequest.model_rebuild()
except NameError:
    pass
