"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel, UNSET_SENTINEL
from pumble_keys.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RemoveReactionRequestTypedDict(TypedDict):
    message_id: str
    reaction: str
    r"""Emoji code in `:emoji_name:` form to remove."""
    channel_id: NotRequired[str]


class RemoveReactionRequest(BaseModel):
    message_id: Annotated[
        str,
        pydantic.Field(alias="messageId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ]

    reaction: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Emoji code in `:emoji_name:` form to remove."""

    channel_id: Annotated[
        Optional[str],
        pydantic.Field(alias="channelId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channelId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RemoveReactionResponseTypedDict(TypedDict):
    r"""Reaction removed."""

    status: NotRequired[str]


class RemoveReactionResponse(BaseModel):
    r"""Reaction removed."""

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
