"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.models import (
    searchmessagesresult as models_searchmessagesresult,
    searchstrategy as models_searchstrategy,
)
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Awaitable, Callable, List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchMessagesRequestTypedDict(TypedDict):
    text: NotRequired[str]
    from_: NotRequired[List[str]]
    r"""Filter by sender user IDs."""
    in_: NotRequired[List[str]]
    r"""Filter by channel IDs or names."""
    limit: NotRequired[int]
    strategy: NotRequired[models_searchstrategy.SearchStrategy]
    before_ts: NotRequired[int]
    r"""Restrict to messages with `timestampMilli` strictly less than this value (also the pagination cursor)."""
    after_ts: NotRequired[int]
    r"""Restrict to messages with `timestampMilli` strictly greater than this value."""


class SearchMessagesRequest(BaseModel):
    text: Optional[str] = None

    from_: Annotated[Optional[List[str]], pydantic.Field(alias="from")] = None
    r"""Filter by sender user IDs."""

    in_: Annotated[Optional[List[str]], pydantic.Field(alias="in")] = None
    r"""Filter by channel IDs or names."""

    limit: Optional[int] = 10

    strategy: Optional[models_searchstrategy.SearchStrategy] = None

    before_ts: Annotated[Optional[int], pydantic.Field(alias="beforeTs")] = None
    r"""Restrict to messages with `timestampMilli` strictly less than this value (also the pagination cursor)."""

    after_ts: Annotated[Optional[int], pydantic.Field(alias="afterTs")] = None
    r"""Restrict to messages with `timestampMilli` strictly greater than this value."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["text", "from", "in", "limit", "strategy", "beforeTs", "afterTs"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SearchMessagesResponseTypedDict(TypedDict):
    result: models_searchmessagesresult.SearchMessagesResultTypedDict


class SearchMessagesResponse(BaseModel):
    next: Union[
        Callable[[], Optional[SearchMessagesResponse]],
        Callable[[], Awaitable[Optional[SearchMessagesResponse]]],
    ]

    result: models_searchmessagesresult.SearchMessagesResult


try:
    SearchMessagesRequest.model_rebuild()
except NameError:
    pass
