"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class SendReplyRequestBody2TypedDict(TypedDict):
    channel: str
    message_id: str
    r"""ID of the message to reply to (the thread root)."""
    text: str
    channel_id: NotRequired[str]
    also_send_to_channel: NotRequired[bool]
    r"""If true, also broadcast the reply to the parent channel."""
    as_bot: NotRequired[bool]


class SendReplyRequestBody2(BaseModel):
    channel: str

    message_id: Annotated[str, pydantic.Field(alias="messageId")]
    r"""ID of the message to reply to (the thread root)."""

    text: str

    channel_id: Annotated[Optional[str], pydantic.Field(alias="channelId")] = None

    also_send_to_channel: Annotated[
        Optional[bool], pydantic.Field(alias="alsoSendToChannel")
    ] = None
    r"""If true, also broadcast the reply to the parent channel."""

    as_bot: Annotated[Optional[bool], pydantic.Field(alias="asBot")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channelId", "alsoSendToChannel", "asBot"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SendReplyRequestBody1TypedDict(TypedDict):
    channel_id: str
    message_id: str
    r"""ID of the message to reply to (the thread root)."""
    text: str
    channel: NotRequired[str]
    also_send_to_channel: NotRequired[bool]
    r"""If true, also broadcast the reply to the parent channel."""
    as_bot: NotRequired[bool]


class SendReplyRequestBody1(BaseModel):
    channel_id: Annotated[str, pydantic.Field(alias="channelId")]

    message_id: Annotated[str, pydantic.Field(alias="messageId")]
    r"""ID of the message to reply to (the thread root)."""

    text: str

    channel: Optional[str] = None

    also_send_to_channel: Annotated[
        Optional[bool], pydantic.Field(alias="alsoSendToChannel")
    ] = None
    r"""If true, also broadcast the reply to the parent channel."""

    as_bot: Annotated[Optional[bool], pydantic.Field(alias="asBot")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channel", "alsoSendToChannel", "asBot"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SendReplyRequestTypedDict = TypeAliasType(
    "SendReplyRequestTypedDict",
    Union[SendReplyRequestBody1TypedDict, SendReplyRequestBody2TypedDict],
)


SendReplyRequest = TypeAliasType(
    "SendReplyRequest", Union[SendReplyRequestBody1, SendReplyRequestBody2]
)


try:
    SendReplyRequestBody2.model_rebuild()
except NameError:
    pass
try:
    SendReplyRequestBody1.model_rebuild()
except NameError:
    pass
