"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.models import messageblock as models_messageblock
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


class SendMessageRequestBody2TypedDict(TypedDict):
    channel: str
    r"""Channel name; ignored if `channelId` is provided."""
    text: str
    channel_id: NotRequired[str]
    thread_root_id: NotRequired[str]
    r"""If set, post as a reply in this thread."""
    as_bot: NotRequired[bool]
    r"""If true, the message is authored by the addon's bot identity instead of the API-key owner."""
    blocks: NotRequired[List[models_messageblock.MessageBlockTypedDict]]
    r"""Pumble rich-text blocks. If provided, takes precedence over `text` for rendering."""


class SendMessageRequestBody2(BaseModel):
    channel: str
    r"""Channel name; ignored if `channelId` is provided."""

    text: str

    channel_id: Annotated[Optional[str], pydantic.Field(alias="channelId")] = None

    thread_root_id: Annotated[Optional[str], pydantic.Field(alias="threadRootId")] = (
        None
    )
    r"""If set, post as a reply in this thread."""

    as_bot: Annotated[Optional[bool], pydantic.Field(alias="asBot")] = None
    r"""If true, the message is authored by the addon's bot identity instead of the API-key owner."""

    blocks: Optional[List[models_messageblock.MessageBlock]] = None
    r"""Pumble rich-text blocks. If provided, takes precedence over `text` for rendering."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channelId", "threadRootId", "asBot", "blocks"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SendMessageRequestBody1TypedDict(TypedDict):
    channel_id: str
    text: str
    channel: NotRequired[str]
    r"""Channel name; ignored if `channelId` is provided."""
    thread_root_id: NotRequired[str]
    r"""If set, post as a reply in this thread."""
    as_bot: NotRequired[bool]
    r"""If true, the message is authored by the addon's bot identity instead of the API-key owner."""
    blocks: NotRequired[List[models_messageblock.MessageBlockTypedDict]]
    r"""Pumble rich-text blocks. If provided, takes precedence over `text` for rendering."""


class SendMessageRequestBody1(BaseModel):
    channel_id: Annotated[str, pydantic.Field(alias="channelId")]

    text: str

    channel: Optional[str] = None
    r"""Channel name; ignored if `channelId` is provided."""

    thread_root_id: Annotated[Optional[str], pydantic.Field(alias="threadRootId")] = (
        None
    )
    r"""If set, post as a reply in this thread."""

    as_bot: Annotated[Optional[bool], pydantic.Field(alias="asBot")] = None
    r"""If true, the message is authored by the addon's bot identity instead of the API-key owner."""

    blocks: Optional[List[models_messageblock.MessageBlock]] = None
    r"""Pumble rich-text blocks. If provided, takes precedence over `text` for rendering."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["channel", "threadRootId", "asBot", "blocks"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


SendMessageRequestTypedDict = TypeAliasType(
    "SendMessageRequestTypedDict",
    Union[SendMessageRequestBody1TypedDict, SendMessageRequestBody2TypedDict],
)


SendMessageRequest = TypeAliasType(
    "SendMessageRequest", Union[SendMessageRequestBody1, SendMessageRequestBody2]
)


try:
    SendMessageRequestBody2.model_rebuild()
except NameError:
    pass
try:
    SendMessageRequestBody1.model_rebuild()
except NameError:
    pass
