"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .pumblesdkbaseerror import PumbleSDKBaseError
from typing import Any, TYPE_CHECKING

from pumble_keys.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .error import Error, ErrorUnion
    from .legacyerror import LegacyError, LegacyErrorData
    from .no_response_error import NoResponseError
    from .pumblesdkerror import PumbleSDKError
    from .responsevalidationerror import ResponseValidationError
    from .structurederror import StructuredError, StructuredErrorData

__all__ = [
    "Error",
    "ErrorUnion",
    "LegacyError",
    "LegacyErrorData",
    "NoResponseError",
    "PumbleSDKBaseError",
    "PumbleSDKError",
    "ResponseValidationError",
    "StructuredError",
    "StructuredErrorData",
]

_dynamic_imports: dict[str, str] = {
    "Error": ".error",
    "ErrorUnion": ".error",
    "LegacyError": ".legacyerror",
    "LegacyErrorData": ".legacyerror",
    "NoResponseError": ".no_response_error",
    "PumbleSDKError": ".pumblesdkerror",
    "ResponseValidationError": ".responsevalidationerror",
    "StructuredError": ".structurederror",
    "StructuredErrorData": ".structurederror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
