"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .legacyerror import LegacyErrorData
from .structurederror import StructuredErrorData
from dataclasses import dataclass, field
import httpx
from pumble_keys.models.errors import PumbleSDKBaseError
from typing import Optional, Union
from typing_extensions import TypeAliasType


ErrorUnion = TypeAliasType("ErrorUnion", Union[LegacyErrorData, StructuredErrorData])
r"""Pumble returns one of two error body shapes; clients should be prepared
to parse either. See the parent operation description for context.

"""


@dataclass(unsafe_hash=True)
class Error(PumbleSDKBaseError):
    r"""Pumble returns one of two error body shapes; clients should be prepared
    to parse either. See the parent operation description for context.

    """

    data: ErrorUnion = field(hash=False)

    def __init__(
        self, data: ErrorUnion, raw_response: httpx.Response, body: Optional[str] = None
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
