"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from pumble_keys.models.errors import PumbleSDKBaseError
from pumble_keys.types import BaseModel
from typing import Optional


class LegacyErrorData(BaseModel):
    error: str
    r"""Human-readable error message."""


@dataclass(unsafe_hash=True)
class LegacyError(PumbleSDKBaseError):
    r"""Free-form error message from the request handler layer."""

    data: LegacyErrorData = field(hash=False)

    def __init__(
        self,
        data: LegacyErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
