"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from pumble_keys.models.errors import PumbleSDKBaseError
from pumble_keys.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated


class StructuredErrorData(BaseModel):
    message: str
    r"""Raw error message."""
    localized_message: Annotated[str, pydantic.Field(alias="localizedMessage")]
    r"""Localized variant of `message` (often identical for English clients)."""
    code: int
    r"""Internal error code."""


@dataclass(unsafe_hash=True)
class StructuredError(PumbleSDKBaseError):
    r"""Structured validation error from the framework layer."""

    data: StructuredErrorData = field(hash=False)

    def __init__(
        self,
        data: StructuredErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
