"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import Any, TYPE_CHECKING

from pumble_keys.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .avatar import Avatar, AvatarTypedDict
    from .channel import Channel, ChannelTypedDict
    from .channellistentry import ChannelListEntry, ChannelListEntryTypedDict
    from .channelref import ChannelRef, ChannelRefTypedDict
    from .channeltype import ChannelType
    from .listmessagesstrategy import ListMessagesStrategy
    from .message import (
        Message,
        MessageThreadReplyInfo,
        MessageThreadReplyInfoTypedDict,
        MessageThreadRootInfo,
        MessageThreadRootInfoTypedDict,
        MessageTypedDict,
    )
    from .messageblock import MessageBlock, MessageBlockTypedDict
    from .messagelist import MessageList, MessageListTypedDict
    from .messageref import MessageRef, MessageRefTypedDict
    from .postingpermissions import PostingPermissions, PostingPermissionsTypedDict
    from .postingpermissionsgroup import PostingPermissionsGroup
    from .reaction import Reaction, ReactionTypedDict
    from .recurrence import Recurrence, RecurrenceTypedDict
    from .recurrencetype import RecurrenceType
    from .richtextelement import RichTextElement, RichTextElementTypedDict
    from .scheduledmessage import (
        ScheduledMessage,
        ScheduledMessageRecurrence,
        ScheduledMessageRecurrenceTypedDict,
        ScheduledMessageTypedDict,
    )
    from .scheduledmessagelist import (
        ScheduledMessageList,
        ScheduledMessageListTypedDict,
    )
    from .scheduledmessageref import ScheduledMessageRef, ScheduledMessageRefTypedDict
    from .searchhit import (
        SearchHit,
        SearchHitThreadReplyInfo,
        SearchHitThreadReplyInfoTypedDict,
        SearchHitThreadRootInfo,
        SearchHitThreadRootInfoTypedDict,
        SearchHitTypedDict,
    )
    from .searchmessagesresult import (
        SearchMessagesResult,
        SearchMessagesResultTypedDict,
    )
    from .searchstrategy import SearchStrategy
    from .security import Security, SecurityTypedDict
    from .user import CustomStatus, CustomStatusTypedDict, User, UserTypedDict
    from .usergroup import UserGroup, UserGroupTypedDict
    from .userrole import UserRole
    from .userstatus import UserStatus
    from . import errors, operations

__all__ = [
    "Avatar",
    "AvatarTypedDict",
    "Channel",
    "ChannelListEntry",
    "ChannelListEntryTypedDict",
    "ChannelRef",
    "ChannelRefTypedDict",
    "ChannelType",
    "ChannelTypedDict",
    "CustomStatus",
    "CustomStatusTypedDict",
    "ListMessagesStrategy",
    "Message",
    "MessageBlock",
    "MessageBlockTypedDict",
    "MessageList",
    "MessageListTypedDict",
    "MessageRef",
    "MessageRefTypedDict",
    "MessageThreadReplyInfo",
    "MessageThreadReplyInfoTypedDict",
    "MessageThreadRootInfo",
    "MessageThreadRootInfoTypedDict",
    "MessageTypedDict",
    "PostingPermissions",
    "PostingPermissionsGroup",
    "PostingPermissionsTypedDict",
    "Reaction",
    "ReactionTypedDict",
    "Recurrence",
    "RecurrenceType",
    "RecurrenceTypedDict",
    "RichTextElement",
    "RichTextElementTypedDict",
    "ScheduledMessage",
    "ScheduledMessageList",
    "ScheduledMessageListTypedDict",
    "ScheduledMessageRecurrence",
    "ScheduledMessageRecurrenceTypedDict",
    "ScheduledMessageRef",
    "ScheduledMessageRefTypedDict",
    "ScheduledMessageTypedDict",
    "SearchHit",
    "SearchHitThreadReplyInfo",
    "SearchHitThreadReplyInfoTypedDict",
    "SearchHitThreadRootInfo",
    "SearchHitThreadRootInfoTypedDict",
    "SearchHitTypedDict",
    "SearchMessagesResult",
    "SearchMessagesResultTypedDict",
    "SearchStrategy",
    "Security",
    "SecurityTypedDict",
    "User",
    "UserGroup",
    "UserGroupTypedDict",
    "UserRole",
    "UserStatus",
    "UserTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "Avatar": ".avatar",
    "AvatarTypedDict": ".avatar",
    "Channel": ".channel",
    "ChannelTypedDict": ".channel",
    "ChannelListEntry": ".channellistentry",
    "ChannelListEntryTypedDict": ".channellistentry",
    "ChannelRef": ".channelref",
    "ChannelRefTypedDict": ".channelref",
    "ChannelType": ".channeltype",
    "ListMessagesStrategy": ".listmessagesstrategy",
    "Message": ".message",
    "MessageThreadReplyInfo": ".message",
    "MessageThreadReplyInfoTypedDict": ".message",
    "MessageThreadRootInfo": ".message",
    "MessageThreadRootInfoTypedDict": ".message",
    "MessageTypedDict": ".message",
    "MessageBlock": ".messageblock",
    "MessageBlockTypedDict": ".messageblock",
    "MessageList": ".messagelist",
    "MessageListTypedDict": ".messagelist",
    "MessageRef": ".messageref",
    "MessageRefTypedDict": ".messageref",
    "PostingPermissions": ".postingpermissions",
    "PostingPermissionsTypedDict": ".postingpermissions",
    "PostingPermissionsGroup": ".postingpermissionsgroup",
    "Reaction": ".reaction",
    "ReactionTypedDict": ".reaction",
    "Recurrence": ".recurrence",
    "RecurrenceTypedDict": ".recurrence",
    "RecurrenceType": ".recurrencetype",
    "RichTextElement": ".richtextelement",
    "RichTextElementTypedDict": ".richtextelement",
    "ScheduledMessage": ".scheduledmessage",
    "ScheduledMessageRecurrence": ".scheduledmessage",
    "ScheduledMessageRecurrenceTypedDict": ".scheduledmessage",
    "ScheduledMessageTypedDict": ".scheduledmessage",
    "ScheduledMessageList": ".scheduledmessagelist",
    "ScheduledMessageListTypedDict": ".scheduledmessagelist",
    "ScheduledMessageRef": ".scheduledmessageref",
    "ScheduledMessageRefTypedDict": ".scheduledmessageref",
    "SearchHit": ".searchhit",
    "SearchHitThreadReplyInfo": ".searchhit",
    "SearchHitThreadReplyInfoTypedDict": ".searchhit",
    "SearchHitThreadRootInfo": ".searchhit",
    "SearchHitThreadRootInfoTypedDict": ".searchhit",
    "SearchHitTypedDict": ".searchhit",
    "SearchMessagesResult": ".searchmessagesresult",
    "SearchMessagesResultTypedDict": ".searchmessagesresult",
    "SearchStrategy": ".searchstrategy",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "CustomStatus": ".user",
    "CustomStatusTypedDict": ".user",
    "User": ".user",
    "UserTypedDict": ".user",
    "UserGroup": ".usergroup",
    "UserGroupTypedDict": ".usergroup",
    "UserRole": ".userrole",
    "UserStatus": ".userstatus",
}

_sub_packages = ["errors", "operations"]


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name,
        package=__package__,
        dynamic_imports=_dynamic_imports,
        sub_packages=_sub_packages,
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports, sub_packages=_sub_packages)
