"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AvatarTypedDict(TypedDict):
    full_path: NotRequired[str]
    scaled_path: NotRequired[str]


class Avatar(BaseModel):
    full_path: Annotated[Optional[str], pydantic.Field(alias="fullPath")] = None

    scaled_path: Annotated[Optional[str], pydantic.Field(alias="scaledPath")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["fullPath", "scaledPath"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Avatar.model_rebuild()
except NameError:
    pass
