"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pumble_keys import utils


class ChannelType(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Visibility of a channel."""

    PUBLIC = "PUBLIC"
    PRIVATE = "PRIVATE"
