"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel
from typing_extensions import TypedDict


class ChannelRefTypedDict(TypedDict):
    r"""Lightweight reference returned by `createChannel`."""

    id: str
    name: str


class ChannelRef(BaseModel):
    r"""Lightweight reference returned by `createChannel`."""

    id: str

    name: str
