"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .channeltype import ChannelType
from .postingpermissions import PostingPermissions, PostingPermissionsTypedDict
from datetime import datetime
from pumble_keys import models
from pumble_keys.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ChannelTypedDict(TypedDict):
    id: str
    name: str
    channel_type: ChannelType
    r"""Visibility of a channel."""
    workspace_id: str
    description: NotRequired[str]
    r"""Optional channel description (empty string if unset)."""
    creator_id: NotRequired[str]
    added_by_id: NotRequired[Nullable[str]]
    r"""User ID that added the current user to the channel (`null` for channels the current user created or that pre-date this tracking)."""
    section_id: NotRequired[str]
    r"""Section the channel belongs to (empty if none)."""
    is_archived: NotRequired[bool]
    is_hidden: NotRequired[bool]
    is_member: NotRequired[bool]
    is_muted: NotRequired[bool]
    is_main: NotRequired[bool]
    is_initial: NotRequired[bool]
    is_addon_bot: NotRequired[bool]
    is_pumble_bot: NotRequired[bool]
    notify_about_replies_in_threads: NotRequired[bool]
    last_message_timestamp: NotRequired[datetime]
    last_message_timestamp_milli: NotRequired[int]
    last_mark_timestamp: NotRequired[datetime]
    last_mark_timestamp_milli: NotRequired[int]
    timestamp: NotRequired[datetime]
    timestamp_milli: NotRequired[int]
    posting_permissions: NotRequired[PostingPermissionsTypedDict]
    desktop_notification_preferences: NotRequired[Nullable[str]]
    r"""Notification preference for this channel on desktop (e.g. `EVERYTHING`, `MENTIONS`, `NONE`); `null` if no per-channel override."""
    mobile_notification_preferences: NotRequired[Nullable[str]]
    r"""Notification preference for this channel on mobile; `null` if no per-channel override."""


class Channel(BaseModel):
    id: str

    name: str

    channel_type: Annotated[ChannelType, pydantic.Field(alias="channelType")]
    r"""Visibility of a channel."""

    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]

    description: Optional[str] = None
    r"""Optional channel description (empty string if unset)."""

    creator_id: Annotated[Optional[str], pydantic.Field(alias="creatorId")] = None

    added_by_id: Annotated[OptionalNullable[str], pydantic.Field(alias="addedById")] = (
        UNSET
    )
    r"""User ID that added the current user to the channel (`null` for channels the current user created or that pre-date this tracking)."""

    section_id: Annotated[Optional[str], pydantic.Field(alias="sectionId")] = None
    r"""Section the channel belongs to (empty if none)."""

    is_archived: Annotated[Optional[bool], pydantic.Field(alias="isArchived")] = None

    is_hidden: Annotated[Optional[bool], pydantic.Field(alias="isHidden")] = None

    is_member: Annotated[Optional[bool], pydantic.Field(alias="isMember")] = None

    is_muted: Annotated[Optional[bool], pydantic.Field(alias="isMuted")] = None

    is_main: Annotated[Optional[bool], pydantic.Field(alias="isMain")] = None

    is_initial: Annotated[Optional[bool], pydantic.Field(alias="isInitial")] = None

    is_addon_bot: Annotated[Optional[bool], pydantic.Field(alias="isAddonBot")] = None

    is_pumble_bot: Annotated[Optional[bool], pydantic.Field(alias="isPumbleBot")] = None

    notify_about_replies_in_threads: Annotated[
        Optional[bool], pydantic.Field(alias="notifyAboutRepliesInThreads")
    ] = None

    last_message_timestamp: Annotated[
        Optional[datetime], pydantic.Field(alias="lastMessageTimestamp")
    ] = None

    last_message_timestamp_milli: Annotated[
        Optional[int], pydantic.Field(alias="lastMessageTimestampMilli")
    ] = None

    last_mark_timestamp: Annotated[
        Optional[datetime], pydantic.Field(alias="lastMarkTimestamp")
    ] = None

    last_mark_timestamp_milli: Annotated[
        Optional[int], pydantic.Field(alias="lastMarkTimestampMilli")
    ] = None

    timestamp: Optional[datetime] = None

    timestamp_milli: Annotated[
        Optional[int], pydantic.Field(alias="timestampMilli")
    ] = None

    posting_permissions: Annotated[
        Optional[PostingPermissions], pydantic.Field(alias="postingPermissions")
    ] = None

    desktop_notification_preferences: Annotated[
        OptionalNullable[str], pydantic.Field(alias="desktopNotificationPreferences")
    ] = UNSET
    r"""Notification preference for this channel on desktop (e.g. `EVERYTHING`, `MENTIONS`, `NONE`); `null` if no per-channel override."""

    mobile_notification_preferences: Annotated[
        OptionalNullable[str], pydantic.Field(alias="mobileNotificationPreferences")
    ] = UNSET
    r"""Notification preference for this channel on mobile; `null` if no per-channel override."""

    @field_serializer("channel_type")
    def serialize_channel_type(self, value):
        if isinstance(value, str):
            try:
                return models.ChannelType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "description",
                "creatorId",
                "addedById",
                "sectionId",
                "isArchived",
                "isHidden",
                "isMember",
                "isMuted",
                "isMain",
                "isInitial",
                "isAddonBot",
                "isPumbleBot",
                "notifyAboutRepliesInThreads",
                "lastMessageTimestamp",
                "lastMessageTimestampMilli",
                "lastMarkTimestamp",
                "lastMarkTimestampMilli",
                "timestamp",
                "timestampMilli",
                "postingPermissions",
                "desktopNotificationPreferences",
                "mobileNotificationPreferences",
            ]
        )
        nullable_fields = set(
            [
                "addedById",
                "desktopNotificationPreferences",
                "mobileNotificationPreferences",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    Channel.model_rebuild()
except NameError:
    pass
