"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .channel import Channel, ChannelTypedDict
from .message import Message, MessageTypedDict
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ChannelListEntryTypedDict(TypedDict):
    r"""`listChannels` returns each channel as a tuple of the channel itself
    plus its pinned messages and member-ID list.

    """

    channel: ChannelTypedDict
    pinned_messages: NotRequired[List[MessageTypedDict]]
    users: NotRequired[List[str]]
    r"""IDs of members of the channel."""


class ChannelListEntry(BaseModel):
    r"""`listChannels` returns each channel as a tuple of the channel itself
    plus its pinned messages and member-ID list.

    """

    channel: Channel

    pinned_messages: Annotated[
        Optional[List[Message]], pydantic.Field(alias="pinnedMessages")
    ] = None

    users: Optional[List[str]] = None
    r"""IDs of members of the channel."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["pinnedMessages", "users"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ChannelListEntry.model_rebuild()
except NameError:
    pass
