"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ListMessagesStrategy(str, Enum):
    r"""Pagination direction relative to `cursor`. When `cursor` is omitted the
    server returns the most-recent page regardless of `strategy`.

    """

    BEFORE = "BEFORE"
    AFTER = "AFTER"
    AROUND = "AROUND"
