"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class MessageRefTypedDict(TypedDict):
    r"""Lightweight reference returned by write operations."""

    id: str
    r"""Server-assigned message identifier (24-char hex)."""
    channel_id: str
    r"""ID of the channel that contains the message."""


class MessageRef(BaseModel):
    r"""Lightweight reference returned by write operations."""

    id: str
    r"""Server-assigned message identifier (24-char hex)."""

    channel_id: Annotated[str, pydantic.Field(alias="channelId")]
    r"""ID of the channel that contains the message."""


try:
    MessageRef.model_rebuild()
except NameError:
    pass
