"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .postingpermissionsgroup import PostingPermissionsGroup
from pumble_keys import models
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostingPermissionsTypedDict(TypedDict):
    allow_threads: NotRequired[bool]
    allow_mentions: NotRequired[bool]
    posting_permissions_group: NotRequired[PostingPermissionsGroup]
    workspace_user_ids: NotRequired[List[str]]


class PostingPermissions(BaseModel):
    allow_threads: Annotated[Optional[bool], pydantic.Field(alias="allowThreads")] = (
        None
    )

    allow_mentions: Annotated[Optional[bool], pydantic.Field(alias="allowMentions")] = (
        None
    )

    posting_permissions_group: Annotated[
        Optional[PostingPermissionsGroup],
        pydantic.Field(alias="postingPermissionsGroup"),
    ] = None

    workspace_user_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="workspaceUserIds")
    ] = None

    @field_serializer("posting_permissions_group")
    def serialize_posting_permissions_group(self, value):
        if isinstance(value, str):
            try:
                return models.PostingPermissionsGroup(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "allowThreads",
                "allowMentions",
                "postingPermissionsGroup",
                "workspaceUserIds",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    PostingPermissions.model_rebuild()
except NameError:
    pass
