"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pumble_keys import utils


class PostingPermissionsGroup(str, Enum, metaclass=utils.OpenEnumMeta):
    EVERYONE = "EVERYONE"
    WORKSPACE_ADMINS = "WORKSPACE_ADMINS"
    SPECIFIC_USERS = "SPECIFIC_USERS"
