"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel
from typing_extensions import TypedDict


class ReactionTypedDict(TypedDict):
    user: str
    r"""User ID that added the reaction."""
    code: str
    r"""Emoji code in `:emoji_name:` form."""


class Reaction(BaseModel):
    user: str
    r"""User ID that added the reaction."""

    code: str
    r"""Emoji code in `:emoji_name:` form."""
