"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .recurrencetype import RecurrenceType
from pumble_keys import models
from pumble_keys.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RecurrenceTypedDict(TypedDict):
    recurrence_type: RecurrenceType
    end_after_occurrences: NotRequired[int]
    end_date: NotRequired[int]
    r"""Epoch-ms after which the recurrence stops."""


class Recurrence(BaseModel):
    recurrence_type: Annotated[RecurrenceType, pydantic.Field(alias="recurrenceType")]

    end_after_occurrences: Annotated[
        Optional[int], pydantic.Field(alias="endAfterOccurrences")
    ] = None

    end_date: Annotated[Optional[int], pydantic.Field(alias="endDate")] = None
    r"""Epoch-ms after which the recurrence stops."""

    @field_serializer("recurrence_type")
    def serialize_recurrence_type(self, value):
        if isinstance(value, str):
            try:
                return models.RecurrenceType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["endAfterOccurrences", "endDate"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    Recurrence.model_rebuild()
except NameError:
    pass
