"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pumble_keys import utils


class RecurrenceType(str, Enum, metaclass=utils.OpenEnumMeta):
    DAILY = "DAILY"
    BUSINESSDAYS = "BUSINESSDAYS"
    WEEKLY = "WEEKLY"
    BIWEEKLY = "BIWEEKLY"
    MONTHLY_NTH_WEEKDAY = "MONTHLY_NTH_WEEKDAY"
    MONTHLY_LAST_WEEKDAY = "MONTHLY_LAST_WEEKDAY"
    QUARTERLY_NTH_WEEKDAY = "QUARTERLY_NTH_WEEKDAY"
    QUARTERLY_LAST_WEEKDAY = "QUARTERLY_LAST_WEEKDAY"
    ANNUALLY = "ANNUALLY"
