"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RichTextElementTypedDict(TypedDict):
    r"""One node in Pumble's rich-text block structure. The full grammar is
    large (Slack-like); only top-level fields are typed here.

    """

    type: NotRequired[str]
    text: NotRequired[str]
    elements: NotRequired[List[RichTextElementTypedDict]]
    highlight: NotRequired[str]
    r"""Present on search-hit blocks to indicate matching text."""


class RichTextElement(BaseModel):
    r"""One node in Pumble's rich-text block structure. The full grammar is
    large (Slack-like); only top-level fields are typed here.

    """

    type: Optional[str] = None

    text: Optional[str] = None

    elements: Optional[List[RichTextElement]] = None

    highlight: Optional[str] = None
    r"""Present on search-hit blocks to indicate matching text."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "text", "elements", "highlight"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
