"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class ScheduledMessageRefTypedDict(TypedDict):
    r"""Lightweight reference returned by `createScheduledMessage`."""

    id: str
    channel_id: str


class ScheduledMessageRef(BaseModel):
    r"""Lightweight reference returned by `createScheduledMessage`."""

    id: str

    channel_id: Annotated[str, pydantic.Field(alias="channelId")]


try:
    ScheduledMessageRef.model_rebuild()
except NameError:
    pass
