"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messageblock import MessageBlock, MessageBlockTypedDict
from .recurrencetype import RecurrenceType
from pumble_keys import models
from pumble_keys.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ScheduledMessageRecurrenceTypedDict(TypedDict):
    recurrence_type: RecurrenceType
    end_after_occurrences: NotRequired[int]
    end_date: NotRequired[int]
    r"""Epoch-ms after which the recurrence stops."""


class ScheduledMessageRecurrence(BaseModel):
    recurrence_type: Annotated[RecurrenceType, pydantic.Field(alias="recurrenceType")]

    end_after_occurrences: Annotated[
        Optional[int], pydantic.Field(alias="endAfterOccurrences")
    ] = None

    end_date: Annotated[Optional[int], pydantic.Field(alias="endDate")] = None
    r"""Epoch-ms after which the recurrence stops."""

    @field_serializer("recurrence_type")
    def serialize_recurrence_type(self, value):
        if isinstance(value, str):
            try:
                return models.RecurrenceType(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["endAfterOccurrences", "endDate"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ScheduledMessageTypedDict(TypedDict):
    id: str
    channel_id: str
    workspace_id: str
    author: str
    text: str
    send_at: int
    r"""Delivery moment (epoch ms)."""
    blocks: NotRequired[List[MessageBlockTypedDict]]
    attachments: NotRequired[List[Dict[str, Any]]]
    files: NotRequired[List[Dict[str, Any]]]
    also_send_to_channel: NotRequired[bool]
    r"""For threaded scheduled messages, whether to also broadcast to the parent channel on send."""
    thread_root_id: NotRequired[Nullable[str]]
    root_text: NotRequired[Nullable[str]]
    quoted_message: NotRequired[Nullable[Dict[str, Any]]]
    recurrence: NotRequired[Nullable[ScheduledMessageRecurrenceTypedDict]]


class ScheduledMessage(BaseModel):
    id: str

    channel_id: Annotated[str, pydantic.Field(alias="channelId")]

    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]

    author: str

    text: str

    send_at: Annotated[int, pydantic.Field(alias="sendAt")]
    r"""Delivery moment (epoch ms)."""

    blocks: Optional[List[MessageBlock]] = None

    attachments: Optional[List[Dict[str, Any]]] = None

    files: Optional[List[Dict[str, Any]]] = None

    also_send_to_channel: Annotated[
        Optional[bool], pydantic.Field(alias="alsoSendToChannel")
    ] = None
    r"""For threaded scheduled messages, whether to also broadcast to the parent channel on send."""

    thread_root_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="threadRootId")
    ] = UNSET

    root_text: Annotated[OptionalNullable[str], pydantic.Field(alias="rootText")] = (
        UNSET
    )

    quoted_message: Annotated[
        OptionalNullable[Dict[str, Any]], pydantic.Field(alias="quotedMessage")
    ] = UNSET

    recurrence: OptionalNullable[ScheduledMessageRecurrence] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "blocks",
                "attachments",
                "files",
                "alsoSendToChannel",
                "threadRootId",
                "rootText",
                "quotedMessage",
                "recurrence",
            ]
        )
        nullable_fields = set(
            ["threadRootId", "rootText", "quotedMessage", "recurrence"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ScheduledMessageRecurrence.model_rebuild()
except NameError:
    pass
try:
    ScheduledMessage.model_rebuild()
except NameError:
    pass
