"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scheduledmessage import ScheduledMessage, ScheduledMessageTypedDict
from pumble_keys.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class ScheduledMessageListTypedDict(TypedDict):
    scheduled_messages: List[ScheduledMessageTypedDict]
    has_more: bool


class ScheduledMessageList(BaseModel):
    scheduled_messages: Annotated[
        List[ScheduledMessage], pydantic.Field(alias="scheduledMessages")
    ]

    has_more: Annotated[bool, pydantic.Field(alias="hasMore")]


try:
    ScheduledMessageList.model_rebuild()
except NameError:
    pass
