"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .searchhit import SearchHit, SearchHitTypedDict
from pumble_keys.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class SearchMessagesResultTypedDict(TypedDict):
    content: List[SearchHitTypedDict]
    total_elements: int
    r"""Total matches across all pages."""
    has_more: bool


class SearchMessagesResult(BaseModel):
    content: List[SearchHit]

    total_elements: Annotated[int, pydantic.Field(alias="totalElements")]
    r"""Total matches across all pages."""

    has_more: Annotated[bool, pydantic.Field(alias="hasMore")]


try:
    SearchMessagesResult.model_rebuild()
except NameError:
    pass
