"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messageblock import MessageBlock, MessageBlockTypedDict
from .reaction import Reaction, ReactionTypedDict
from datetime import datetime
from pumble_keys.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class SearchHitThreadRootInfoTypedDict(TypedDict):
    reply_count: NotRequired[int]
    last_reply_timestamp_milli: NotRequired[int]


class SearchHitThreadRootInfo(BaseModel):
    reply_count: Annotated[Optional[int], pydantic.Field(alias="replyCount")] = None

    last_reply_timestamp_milli: Annotated[
        Optional[int], pydantic.Field(alias="lastReplyTimestampMilli")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["replyCount", "lastReplyTimestampMilli"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SearchHitThreadReplyInfoTypedDict(TypedDict):
    root_id: NotRequired[str]
    reply_sent_to_channel: NotRequired[bool]
    root_text: NotRequired[str]


class SearchHitThreadReplyInfo(BaseModel):
    root_id: Annotated[Optional[str], pydantic.Field(alias="rootId")] = None

    reply_sent_to_channel: Annotated[
        Optional[bool], pydantic.Field(alias="replySentToChannel")
    ] = None

    root_text: Annotated[Optional[str], pydantic.Field(alias="rootText")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["rootId", "replySentToChannel", "rootText"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class SearchHitTypedDict(TypedDict):
    id: str
    channel_id: str
    workspace_id: str
    author: str
    r"""ID of the user (or addon) that sent the message."""
    text: str
    timestamp: datetime
    timestamp_milli: int
    author_app_id: NotRequired[Nullable[str]]
    r"""ID of the addon app that authored the message (null for human-authored)."""
    blocks: NotRequired[Nullable[List[MessageBlockTypedDict]]]
    attachments: NotRequired[List[Dict[str, Any]]]
    files: NotRequired[List[Dict[str, Any]]]
    reactions: NotRequired[List[ReactionTypedDict]]
    link_previews: NotRequired[List[Dict[str, Any]]]
    thread_root_info: NotRequired[Nullable[SearchHitThreadRootInfoTypedDict]]
    thread_reply_info: NotRequired[Nullable[SearchHitThreadReplyInfoTypedDict]]
    deleted: NotRequired[bool]
    edited: NotRequired[bool]
    is_following: NotRequired[bool]
    subtype: NotRequired[str]
    r"""Message subtype (empty string for normal messages)."""
    local_id: NotRequired[str]
    meta: NotRequired[Nullable[Dict[str, Any]]]
    saved_timestamp_milli: NotRequired[int]
    highlighted_blocks: NotRequired[List[MessageBlockTypedDict]]
    r"""Same as `blocks`, with `highlight` annotations on matching text segments."""


class SearchHit(BaseModel):
    id: str

    channel_id: Annotated[str, pydantic.Field(alias="channelId")]

    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]

    author: str
    r"""ID of the user (or addon) that sent the message."""

    text: str

    timestamp: datetime

    timestamp_milli: Annotated[int, pydantic.Field(alias="timestampMilli")]

    author_app_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="authorAppId")
    ] = UNSET
    r"""ID of the addon app that authored the message (null for human-authored)."""

    blocks: OptionalNullable[List[MessageBlock]] = UNSET

    attachments: Optional[List[Dict[str, Any]]] = None

    files: Optional[List[Dict[str, Any]]] = None

    reactions: Optional[List[Reaction]] = None

    link_previews: Annotated[
        Optional[List[Dict[str, Any]]], pydantic.Field(alias="linkPreviews")
    ] = None

    thread_root_info: Annotated[
        OptionalNullable[SearchHitThreadRootInfo],
        pydantic.Field(alias="threadRootInfo"),
    ] = UNSET

    thread_reply_info: Annotated[
        OptionalNullable[SearchHitThreadReplyInfo],
        pydantic.Field(alias="threadReplyInfo"),
    ] = UNSET

    deleted: Optional[bool] = None

    edited: Optional[bool] = None

    is_following: Annotated[Optional[bool], pydantic.Field(alias="isFollowing")] = None

    subtype: Optional[str] = None
    r"""Message subtype (empty string for normal messages)."""

    local_id: Annotated[Optional[str], pydantic.Field(alias="localId")] = None

    meta: OptionalNullable[Dict[str, Any]] = UNSET

    saved_timestamp_milli: Annotated[
        Optional[int], pydantic.Field(alias="savedTimestampMilli")
    ] = None

    highlighted_blocks: Annotated[
        Optional[List[MessageBlock]], pydantic.Field(alias="highlightedBlocks")
    ] = None
    r"""Same as `blocks`, with `highlight` annotations on matching text segments."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "authorAppId",
                "blocks",
                "attachments",
                "files",
                "reactions",
                "linkPreviews",
                "threadRootInfo",
                "threadReplyInfo",
                "deleted",
                "edited",
                "isFollowing",
                "subtype",
                "localId",
                "meta",
                "savedTimestampMilli",
                "highlightedBlocks",
            ]
        )
        nullable_fields = set(
            ["authorAppId", "blocks", "threadRootInfo", "threadReplyInfo", "meta"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    SearchHitThreadRootInfo.model_rebuild()
except NameError:
    pass
try:
    SearchHitThreadReplyInfo.model_rebuild()
except NameError:
    pass
try:
    SearchHit.model_rebuild()
except NameError:
    pass
