"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class SearchStrategy(str, Enum):
    MOST_RELEVANT = "MOST_RELEVANT"
    MOST_RECENT = "MOST_RECENT"
    NEWEST = "NEWEST"
    OLDEST = "OLDEST"
