"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pumble_keys.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UserGroupTypedDict(TypedDict):
    id: str
    name: str
    handle: str
    workspace_id: str
    description: NotRequired[Nullable[str]]
    disabled: NotRequired[bool]
    created_by: NotRequired[str]
    workspace_user_ids: NotRequired[List[str]]


class UserGroup(BaseModel):
    id: str

    name: str

    handle: str

    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]

    description: OptionalNullable[str] = UNSET

    disabled: Optional[bool] = None

    created_by: Annotated[Optional[str], pydantic.Field(alias="createdBy")] = None

    workspace_user_ids: Annotated[
        Optional[List[str]], pydantic.Field(alias="workspaceUserIds")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["description", "disabled", "createdBy", "workspaceUserIds"]
        )
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    UserGroup.model_rebuild()
except NameError:
    pass
