"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .avatar import Avatar, AvatarTypedDict
from .userrole import UserRole
from .userstatus import UserStatus
from pumble_keys import models
from pumble_keys.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import field_serializer, model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CustomStatusTypedDict(TypedDict):
    r"""A user's custom status (the value, not the update payload)."""

    code: NotRequired[str]
    r"""Emoji code in `:emoji_name:` form."""
    status: NotRequired[str]
    r"""Free-form status text."""
    expiration: NotRequired[str]
    r"""Expiration mode (e.g. `custom`, `dont_clear`)."""
    expires_at: NotRequired[int]
    r"""Epoch-ms moment the status auto-clears (0 if never)."""
    show_until: NotRequired[bool]


class CustomStatus(BaseModel):
    r"""A user's custom status (the value, not the update payload)."""

    code: Optional[str] = None
    r"""Emoji code in `:emoji_name:` form."""

    status: Optional[str] = None
    r"""Free-form status text."""

    expiration: Optional[str] = None
    r"""Expiration mode (e.g. `custom`, `dont_clear`)."""

    expires_at: Annotated[Optional[int], pydantic.Field(alias="expiresAt")] = None
    r"""Epoch-ms moment the status auto-clears (0 if never)."""

    show_until: Annotated[Optional[bool], pydantic.Field(alias="showUntil")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["code", "status", "expiration", "expiresAt", "showUntil"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UserTypedDict(TypedDict):
    id: str
    email: str
    name: str
    role: UserRole
    r"""Workspace role."""
    status: UserStatus
    r"""Lifecycle state of a workspace user."""
    workspace_id: str
    phone: NotRequired[str]
    title: NotRequired[str]
    r"""User's job title (empty string if unset)."""
    avatar: NotRequired[AvatarTypedDict]
    custom_status: NotRequired[Nullable[CustomStatusTypedDict]]
    time_zone_id: NotRequired[str]
    automatically_time_zone: NotRequired[bool]
    active_until: NotRequired[int]
    is_addon_bot: NotRequired[bool]
    is_pumble_bot: NotRequired[bool]
    invited_by: NotRequired[Nullable[str]]
    broadcast_warning_shown_ts: NotRequired[Nullable[int]]


class User(BaseModel):
    id: str

    email: str

    name: str

    role: UserRole
    r"""Workspace role."""

    status: UserStatus
    r"""Lifecycle state of a workspace user."""

    workspace_id: Annotated[str, pydantic.Field(alias="workspaceId")]

    phone: Optional[str] = None

    title: Optional[str] = None
    r"""User's job title (empty string if unset)."""

    avatar: Optional[Avatar] = None

    custom_status: Annotated[
        OptionalNullable[CustomStatus], pydantic.Field(alias="customStatus")
    ] = UNSET

    time_zone_id: Annotated[Optional[str], pydantic.Field(alias="timeZoneId")] = None

    automatically_time_zone: Annotated[
        Optional[bool], pydantic.Field(alias="automaticallyTimeZone")
    ] = None

    active_until: Annotated[Optional[int], pydantic.Field(alias="activeUntil")] = None

    is_addon_bot: Annotated[Optional[bool], pydantic.Field(alias="isAddonBot")] = None

    is_pumble_bot: Annotated[Optional[bool], pydantic.Field(alias="isPumbleBot")] = None

    invited_by: Annotated[OptionalNullable[str], pydantic.Field(alias="invitedBy")] = (
        UNSET
    )

    broadcast_warning_shown_ts: Annotated[
        OptionalNullable[int], pydantic.Field(alias="broadcastWarningShownTs")
    ] = UNSET

    @field_serializer("role")
    def serialize_role(self, value):
        if isinstance(value, str):
            try:
                return models.UserRole(value)
            except ValueError:
                return value
        return value

    @field_serializer("status")
    def serialize_status(self, value):
        if isinstance(value, str):
            try:
                return models.UserStatus(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "phone",
                "title",
                "avatar",
                "customStatus",
                "timeZoneId",
                "automaticallyTimeZone",
                "activeUntil",
                "isAddonBot",
                "isPumbleBot",
                "invitedBy",
                "broadcastWarningShownTs",
            ]
        )
        nullable_fields = set(["customStatus", "invitedBy", "broadcastWarningShownTs"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    CustomStatus.model_rebuild()
except NameError:
    pass
try:
    User.model_rebuild()
except NameError:
    pass
