"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from pumble_keys import utils


class UserStatus(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""Lifecycle state of a workspace user."""

    ACTIVATED = "ACTIVATED"
    DEACTIVATED = "DEACTIVATED"
    INVITED = "INVITED"
