workflowVersion: 1.0.0
speakeasyVersion: 1.763.6
sources:
    pumble-openapi:
        inputs:
            - location: ./PumbleOpenApi.yaml
        registry:
            location: registry.speakeasyapi.dev/apet115/apet115-wt/pumble-openapi
targets:
    pumble-keys-python:
        target: python
        source: pumble-openapi
