"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from jsonpath import JSONPath
from pumble_keys import models, utils
from pumble_keys._hooks import HookContext
from pumble_keys.types import OptionalNullable, UNSET
from pumble_keys.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Awaitable, Dict, Iterable, List, Mapping, Optional, Union


class ScheduledMessages(BaseSDK):
    r"""Manage messages queued for future delivery, with optional recurrence."""

    def create_scheduled_message(
        self,
        *,
        channel_id: str,
        text: str,
        send_at: int,
        blocks: Optional[
            Union[Iterable[models.MessageBlock], Iterable[models.MessageBlockTypedDict]]
        ] = None,
        thread_root_id: Optional[str] = None,
        also_send_to_channel: Optional[bool] = None,
        recurrence: Optional[
            Union[models.Recurrence, models.RecurrenceTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ScheduledMessageRef:
        r"""Create a scheduled (future) message

        :param channel_id:
        :param text:
        :param send_at: Delivery moment (epoch ms). Must be in the future.
        :param blocks:
        :param thread_root_id: If set, the scheduled message will be sent as a thread reply.
        :param also_send_to_channel:
        :param recurrence:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.CreateScheduledMessageRequest(
            channel_id=channel_id,
            text=text,
            send_at=send_at,
            blocks=utils.get_pydantic_model(
                blocks, Optional[List[models.MessageBlock]]
            ),
            thread_root_id=thread_root_id,
            also_send_to_channel=also_send_to_channel,
            recurrence=utils.get_pydantic_model(
                recurrence, Optional[models.Recurrence]
            ),
        )

        req = self._build_request(
            method="POST",
            path="/createScheduledMessage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request,
                False,
                False,
                "json",
                models.operations.CreateScheduledMessageRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="createScheduledMessage",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Scheduled Messages"],
                extensions={"x-sdk-no-write-retries": True},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ScheduledMessageRef, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(models.errors.ErrorUnion, http_res)
            raise models.errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.PumbleSDKError("Unexpected response received", http_res)

    async def create_scheduled_message_async(
        self,
        *,
        channel_id: str,
        text: str,
        send_at: int,
        blocks: Optional[
            Union[Iterable[models.MessageBlock], Iterable[models.MessageBlockTypedDict]]
        ] = None,
        thread_root_id: Optional[str] = None,
        also_send_to_channel: Optional[bool] = None,
        recurrence: Optional[
            Union[models.Recurrence, models.RecurrenceTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ScheduledMessageRef:
        r"""Create a scheduled (future) message

        :param channel_id:
        :param text:
        :param send_at: Delivery moment (epoch ms). Must be in the future.
        :param blocks:
        :param thread_root_id: If set, the scheduled message will be sent as a thread reply.
        :param also_send_to_channel:
        :param recurrence:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.CreateScheduledMessageRequest(
            channel_id=channel_id,
            text=text,
            send_at=send_at,
            blocks=utils.get_pydantic_model(
                blocks, Optional[List[models.MessageBlock]]
            ),
            thread_root_id=thread_root_id,
            also_send_to_channel=also_send_to_channel,
            recurrence=utils.get_pydantic_model(
                recurrence, Optional[models.Recurrence]
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/createScheduledMessage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request,
                False,
                False,
                "json",
                models.operations.CreateScheduledMessageRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="createScheduledMessage",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Scheduled Messages"],
                extensions={"x-sdk-no-write-retries": True},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ScheduledMessageRef, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(models.errors.ErrorUnion, http_res)
            raise models.errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.PumbleSDKError("Unexpected response received", http_res)

    def fetch_scheduled_messages(
        self,
        *,
        channel_id: Optional[str] = None,
        cursor: Optional[str] = None,
        limit: Optional[int] = 100,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Optional[models.operations.FetchScheduledMessagesResponse]:
        r"""Fetch a list of scheduled messages

        Returns scheduled messages for the workspace (optionally filtered to
        a single channel). Cursor pagination uses the last scheduled
        message's `id`.


        :param channel_id:
        :param cursor:
        :param limit:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.FetchScheduledMessagesRequest(
            channel_id=channel_id,
            cursor=cursor,
            limit=limit,
        )

        req = self._build_request(
            method="GET",
            path="/fetchScheduledMessages",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 30000, 1.5, 60000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5XX"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="fetchScheduledMessages",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Scheduled Messages"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        def next_func() -> Optional[models.operations.FetchScheduledMessagesResponse]:
            body = utils.unmarshal_json(http_res.text, Union[Dict[Any, Any], List[Any]])

            next_cursor = JSONPath("$.scheduledMessages[-1].id").parse(body)

            if len(next_cursor) == 0:
                return None

            next_cursor = next_cursor[0]
            if next_cursor is None or str(next_cursor).strip() == "":
                return None
            results = JSONPath("$.scheduledMessages").parse(body)
            if len(results) == 0 or len(results[0]) == 0:
                return None

            return self.fetch_scheduled_messages(
                channel_id=channel_id,
                cursor=next_cursor,
                limit=limit,
                retries=retries,
                server_url=server_url,
                timeout_ms=timeout_ms,
                http_headers=http_headers,
            )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.operations.FetchScheduledMessagesResponse(
                result=unmarshal_json_response(models.ScheduledMessageList, http_res),
                next=next_func,
            )
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(models.errors.ErrorUnion, http_res)
            raise models.errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.PumbleSDKError("Unexpected response received", http_res)

    async def fetch_scheduled_messages_async(
        self,
        *,
        channel_id: Optional[str] = None,
        cursor: Optional[str] = None,
        limit: Optional[int] = 100,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> Optional[models.operations.FetchScheduledMessagesResponse]:
        r"""Fetch a list of scheduled messages

        Returns scheduled messages for the workspace (optionally filtered to
        a single channel). Cursor pagination uses the last scheduled
        message's `id`.


        :param channel_id:
        :param cursor:
        :param limit:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.FetchScheduledMessagesRequest(
            channel_id=channel_id,
            cursor=cursor,
            limit=limit,
        )

        req = self._build_request_async(
            method="GET",
            path="/fetchScheduledMessages",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 30000, 1.5, 60000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5XX"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="fetchScheduledMessages",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Scheduled Messages"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        def next_func() -> (
            Awaitable[Optional[models.operations.FetchScheduledMessagesResponse]]
        ):
            body = utils.unmarshal_json(http_res.text, Union[Dict[Any, Any], List[Any]])

            async def empty_result():
                return None

            next_cursor = JSONPath("$.scheduledMessages[-1].id").parse(body)

            if len(next_cursor) == 0:
                return empty_result()

            next_cursor = next_cursor[0]
            if next_cursor is None or str(next_cursor).strip() == "":
                return empty_result()
            results = JSONPath("$.scheduledMessages").parse(body)
            if len(results) == 0 or len(results[0]) == 0:
                return empty_result()

            return self.fetch_scheduled_messages_async(
                channel_id=channel_id,
                cursor=next_cursor,
                limit=limit,
                retries=retries,
                server_url=server_url,
                timeout_ms=timeout_ms,
                http_headers=http_headers,
            )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.operations.FetchScheduledMessagesResponse(
                result=unmarshal_json_response(models.ScheduledMessageList, http_res),
                next=next_func,
            )
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(models.errors.ErrorUnion, http_res)
            raise models.errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.PumbleSDKError("Unexpected response received", http_res)

    def fetch_scheduled_message(
        self,
        *,
        scheduled_message_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ScheduledMessage:
        r"""Fetch a single scheduled message by ID

        :param scheduled_message_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.FetchScheduledMessageRequest(
            scheduled_message_id=scheduled_message_id,
        )

        req = self._build_request(
            method="GET",
            path="/fetchScheduledMessage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 30000, 1.5, 60000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5XX"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="fetchScheduledMessage",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Scheduled Messages"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ScheduledMessage, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(models.errors.ErrorUnion, http_res)
            raise models.errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.PumbleSDKError("Unexpected response received", http_res)

    async def fetch_scheduled_message_async(
        self,
        *,
        scheduled_message_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ScheduledMessage:
        r"""Fetch a single scheduled message by ID

        :param scheduled_message_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.FetchScheduledMessageRequest(
            scheduled_message_id=scheduled_message_id,
        )

        req = self._build_request_async(
            method="GET",
            path="/fetchScheduledMessage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config
            else:
                retries = utils.RetryConfig(
                    "backoff", utils.BackoffStrategy(500, 30000, 1.5, 60000), True
                )

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "5XX"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="fetchScheduledMessage",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Scheduled Messages"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ScheduledMessage, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(models.errors.ErrorUnion, http_res)
            raise models.errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.PumbleSDKError("Unexpected response received", http_res)

    def edit_scheduled_message(
        self,
        *,
        scheduled_message_id: str,
        channel_id: str,
        text: str,
        send_at: int,
        blocks: Optional[
            Union[Iterable[models.MessageBlock], Iterable[models.MessageBlockTypedDict]]
        ] = None,
        recurrence: Optional[
            Union[models.Recurrence, models.RecurrenceTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ScheduledMessage:
        r"""Edit a scheduled message

        Updates a queued scheduled message. **All of** `scheduledMessageId`,
        `channelId`, `text`, and `sendAt` are required server-side — omitting
        any of them returns 403 with `[must not be null]`. Pass the existing
        `sendAt` value verbatim if you don't want to reschedule.


        :param scheduled_message_id:
        :param channel_id:
        :param text:
        :param send_at: Delivery moment (epoch ms). Required even if unchanged.
        :param blocks:
        :param recurrence:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.EditScheduledMessageRequest(
            scheduled_message_id=scheduled_message_id,
            channel_id=channel_id,
            text=text,
            send_at=send_at,
            blocks=utils.get_pydantic_model(
                blocks, Optional[List[models.MessageBlock]]
            ),
            recurrence=utils.get_pydantic_model(
                recurrence, Optional[models.Recurrence]
            ),
        )

        req = self._build_request(
            method="POST",
            path="/editScheduledMessage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request,
                False,
                False,
                "json",
                models.operations.EditScheduledMessageRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="editScheduledMessage",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Scheduled Messages"],
                extensions={"x-sdk-no-write-retries": True},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ScheduledMessage, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(models.errors.ErrorUnion, http_res)
            raise models.errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.PumbleSDKError("Unexpected response received", http_res)

    async def edit_scheduled_message_async(
        self,
        *,
        scheduled_message_id: str,
        channel_id: str,
        text: str,
        send_at: int,
        blocks: Optional[
            Union[Iterable[models.MessageBlock], Iterable[models.MessageBlockTypedDict]]
        ] = None,
        recurrence: Optional[
            Union[models.Recurrence, models.RecurrenceTypedDict]
        ] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ScheduledMessage:
        r"""Edit a scheduled message

        Updates a queued scheduled message. **All of** `scheduledMessageId`,
        `channelId`, `text`, and `sendAt` are required server-side — omitting
        any of them returns 403 with `[must not be null]`. Pass the existing
        `sendAt` value verbatim if you don't want to reschedule.


        :param scheduled_message_id:
        :param channel_id:
        :param text:
        :param send_at: Delivery moment (epoch ms). Required even if unchanged.
        :param blocks:
        :param recurrence:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.EditScheduledMessageRequest(
            scheduled_message_id=scheduled_message_id,
            channel_id=channel_id,
            text=text,
            send_at=send_at,
            blocks=utils.get_pydantic_model(
                blocks, Optional[List[models.MessageBlock]]
            ),
            recurrence=utils.get_pydantic_model(
                recurrence, Optional[models.Recurrence]
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/editScheduledMessage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request,
                False,
                False,
                "json",
                models.operations.EditScheduledMessageRequest,
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="editScheduledMessage",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Scheduled Messages"],
                extensions={"x-sdk-no-write-retries": True},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ScheduledMessage, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(models.errors.ErrorUnion, http_res)
            raise models.errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.PumbleSDKError("Unexpected response received", http_res)

    def delete_scheduled_message(
        self,
        *,
        scheduled_message_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ):
        r"""Delete a scheduled message

        :param scheduled_message_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.DeleteScheduledMessageRequest(
            scheduled_message_id=scheduled_message_id,
        )

        req = self._build_request(
            method="DELETE",
            path="/deleteScheduledMessage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="deleteScheduledMessage",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Scheduled Messages"],
                extensions={"x-sdk-no-write-retries": True},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "*"):
            return
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(models.errors.ErrorUnion, http_res)
            raise models.errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.PumbleSDKError("Unexpected response received", http_res)

    async def delete_scheduled_message_async(
        self,
        *,
        scheduled_message_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ):
        r"""Delete a scheduled message

        :param scheduled_message_id:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.operations.DeleteScheduledMessageRequest(
            scheduled_message_id=scheduled_message_id,
        )

        req = self._build_request_async(
            method="DELETE",
            path="/deleteScheduledMessage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="deleteScheduledMessage",
                oauth2_scopes=None,
                security_source=self.sdk_configuration.security,
                tags=["Scheduled Messages"],
                extensions={"x-sdk-no-write-retries": True},
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "*"):
            return
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(models.errors.ErrorUnion, http_res)
            raise models.errors.Error(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.errors.PumbleSDKError(
                "API error occurred", http_res, http_res_text
            )

        raise models.errors.PumbleSDKError("Unexpected response received", http_res)
